name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@77.232.136.158 << 'EOF'
            cd /root/projects/adekkdev-front
            git pull origin main
            docker-compose down
            docker-compose run --rm frontend npm install
            docker-compose up --build -d
          EOF
